services:
  
  App.Context.User.domain.UserRepository:
    class:  ../../Context/User/infrastructure/DumpUserRepository
    arguments: []
  
  App.Context.User.application.UserCreator:
    class: ../../Context/User/application/UserCreator
    arguments: ["@App.Context.User.domain.UserRepository"]
