name: TS Backend DDD Skeleton CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [5.0]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Build the app
        run: |
          npm run build --if-present
          npm run lint
          npm run build:clean
      - name: Run tests
        run: |
          npm test